project_name: lazypassword

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: lazypassword
    repository:
      owner: ToEzBit
      name: homebrew-lazypassword
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/ToEzBit/lazypassword"
    description: "Password management tool for lazy people"
    license: "MIT"
    install: |
      bin.install "lazypassword"
